currentId = f79d6a26-fdbb-4301-866d-1c8932d9a7b9

#Accept: text/xml; charset=utf-8
--

http://localhost:3000
Content-Type: application/json; charset=utf-8
GET /api/assessment?name=six&limit=3

http://localhost:3000
Content-Type: application/json; charset=utf-8
GET /api/assessment/:currentId

http://localhost:3000
Content-Type: application/json; charset=utf-8
GET /api/assessment?name=one
GET /api/assessment?name=two
GET /api/assessment?name=three

http://localhost:3000
Content-Type: application/json; charset=utf-8
POST /api/assessment
{"name": "six", "value": 88.11}

http://localhost:3000
Content-Type: application/json; charset=utf-8
DELETE /api/assessment/:currentId


